name: dashboard-build
on:
  workflow_dispatch:
    inputs:
      info:
        description: 'Info'
        default: 'No need to select branch'
      environment:
        type: choice
        description: Select Environment
        options:
        - dev
        - qa
        - uat
        - prod
        required: true 
   
jobs:          
  build-random:
    name: Build lo
    runs-on:  [self-hosted, linux, APPE]
    environment: ${{github.event.inputs.environment}}
    env:
      RESOLVED_NODE_ENV: ''
    steps:
      - name: Setup Node Environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" == 'dev' ]]; then
            echo "RESOLVED_NODE_ENV=development" >> $GITHUB_ENV
          else
            echo "RESOLVED_NODE_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi
          
      - name: Echo ENV
        env:
          NODE_ENV : $RESOLVED_NODE_ENV
        run: |
          echo "${{env.NODE_ENV}}"
          
